services:
  app:
    container_name:
      p_simple_shop
    build:
      context: 
        .
      dockerfile: 
        Dockerfile
    command:
      uvicorn app.main:app --reload --host 0.0.0.0 --port ${APP_PORT}
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - backend
    depends_on:
      - migration
  
  db:
    container_name:
      postgres
    image: 
      postgres:16
    restart:
      "always"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend
    volumes:
      - ${POSTGRES_VOLUME}:/pg_volume/db_here

  migration:
    container_name:
      migration
    build:
      context:
        .
      dockerfile:
        Dockerfile
    command:
      alembic upgrade head
    depends_on:
      - db
    restart:
      "no"
    networks:
      - backend

networks:
  backend:
    
volumes:
  ${POSTGRES_VOLUME}: